name: Build index
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-index
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: tetrateio/circle-checkout@00b04808a3e5c1c3f736c8f7db59f2ab7b97635a # v1.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: gh-pages
          token: ${{ secrets.GH_TOKEN }}
      - name: Install releaser
        run: |
          # install required binaries
          curl -fSsL https://tetrateio.github.io/tis-releaser/install.sh | sudo TIS_RELEASER_INSTALL=/usr/local bash
          curl -fsSL https://get.helm.sh/helm-v3.13.2-linux-amd64.tar.gz | sudo tar xz --strip-components=1 linux-amd64/helm -C /usr/local/bin
      - name: Build index
        run: |
          tis-releaser release charts -d charts --merge gh-pages/index.yaml ${{ github.ref == 'refs/heads/main' && '--upload' || '' }}
          cp -f work/dist/charts/index.yaml gh-pages/index.yaml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GCLOUD_SKIP: "true"
      - if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          commit_message: Apply automatic update for index.yaml
          branch: gh-pages
          repository: gh-pages
          commit_user_name: tetrate-ci
          commit_user_email: 52504619+tetrate-ci@users.noreply.github.com
          commit_author: tetrate-ci <52504619+tetrate-ci@users.noreply.github.com>
